/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppWithdrawalsRouteImport } from './routes/app/withdrawals'
import { Route as AppTransactionsRouteImport } from './routes/app/transactions'
import { Route as AppSupportRouteImport } from './routes/app/support'
import { Route as AppSellsRouteImport } from './routes/app/sells'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppPrivacyRouteImport } from './routes/app/privacy'
import { Route as AppMarketRouteImport } from './routes/app/market'
import { Route as AppDepositRouteImport } from './routes/app/deposit'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin.index'
import { Route as AppTransactionsTxIdRouteImport } from './routes/app/transactions.$txId'
import { Route as AppAdminWithdrawalsRouteImport } from './routes/app/admin.withdrawals'
import { Route as AppAdminUsersRouteImport } from './routes/app/admin.users'
import { Route as AppAdminProductsRouteImport } from './routes/app/admin.products'
import { Route as AppAdminDepositsRouteImport } from './routes/app/admin.deposits'
import { Route as AppAdminContentRouteImport } from './routes/app/admin.content'
import { Route as ApiPublicFxRefreshRouteImport } from './routes/api/public/fx-refresh'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWithdrawalsRoute = AppWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSellsRoute = AppSellsRouteImport.update({
  id: '/sells',
  path: '/sells',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositRoute = AppDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsTxIdRoute = AppTransactionsTxIdRouteImport.update({
  id: '/$txId',
  path: '/$txId',
  getParentRoute: () => AppTransactionsRoute,
} as any)
const AppAdminWithdrawalsRoute = AppAdminWithdrawalsRouteImport.update({
  id: '/admin/withdrawals',
  path: '/admin/withdrawals',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminProductsRoute = AppAdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDepositsRoute = AppAdminDepositsRouteImport.update({
  id: '/admin/deposits',
  path: '/admin/deposits',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminContentRoute = AppAdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicFxRefreshRoute = ApiPublicFxRefreshRouteImport.update({
  id: '/api/public/fx-refresh',
  path: '/api/public/fx-refresh',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/market': typeof AppMarketRoute
  '/app/privacy': typeof AppPrivacyRoute
  '/app/profile': typeof AppProfileRoute
  '/app/sells': typeof AppSellsRoute
  '/app/support': typeof AppSupportRoute
  '/app/transactions': typeof AppTransactionsRouteWithChildren
  '/app/withdrawals': typeof AppWithdrawalsRoute
  '/app/': typeof AppIndexRoute
  '/api/public/fx-refresh': typeof ApiPublicFxRefreshRoute
  '/app/admin/content': typeof AppAdminContentRoute
  '/app/admin/deposits': typeof AppAdminDepositsRoute
  '/app/admin/products': typeof AppAdminProductsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/withdrawals': typeof AppAdminWithdrawalsRoute
  '/app/transactions/$txId': typeof AppTransactionsTxIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/market': typeof AppMarketRoute
  '/app/privacy': typeof AppPrivacyRoute
  '/app/profile': typeof AppProfileRoute
  '/app/sells': typeof AppSellsRoute
  '/app/support': typeof AppSupportRoute
  '/app/transactions': typeof AppTransactionsRouteWithChildren
  '/app/withdrawals': typeof AppWithdrawalsRoute
  '/app': typeof AppIndexRoute
  '/api/public/fx-refresh': typeof ApiPublicFxRefreshRoute
  '/app/admin/content': typeof AppAdminContentRoute
  '/app/admin/deposits': typeof AppAdminDepositsRoute
  '/app/admin/products': typeof AppAdminProductsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/withdrawals': typeof AppAdminWithdrawalsRoute
  '/app/transactions/$txId': typeof AppTransactionsTxIdRoute
  '/app/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/market': typeof AppMarketRoute
  '/app/privacy': typeof AppPrivacyRoute
  '/app/profile': typeof AppProfileRoute
  '/app/sells': typeof AppSellsRoute
  '/app/support': typeof AppSupportRoute
  '/app/transactions': typeof AppTransactionsRouteWithChildren
  '/app/withdrawals': typeof AppWithdrawalsRoute
  '/app/': typeof AppIndexRoute
  '/api/public/fx-refresh': typeof ApiPublicFxRefreshRoute
  '/app/admin/content': typeof AppAdminContentRoute
  '/app/admin/deposits': typeof AppAdminDepositsRoute
  '/app/admin/products': typeof AppAdminProductsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/withdrawals': typeof AppAdminWithdrawalsRoute
  '/app/transactions/$txId': typeof AppTransactionsTxIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/deposit'
    | '/app/market'
    | '/app/privacy'
    | '/app/profile'
    | '/app/sells'
    | '/app/support'
    | '/app/transactions'
    | '/app/withdrawals'
    | '/app/'
    | '/api/public/fx-refresh'
    | '/app/admin/content'
    | '/app/admin/deposits'
    | '/app/admin/products'
    | '/app/admin/users'
    | '/app/admin/withdrawals'
    | '/app/transactions/$txId'
    | '/app/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app/deposit'
    | '/app/market'
    | '/app/privacy'
    | '/app/profile'
    | '/app/sells'
    | '/app/support'
    | '/app/transactions'
    | '/app/withdrawals'
    | '/app'
    | '/api/public/fx-refresh'
    | '/app/admin/content'
    | '/app/admin/deposits'
    | '/app/admin/products'
    | '/app/admin/users'
    | '/app/admin/withdrawals'
    | '/app/transactions/$txId'
    | '/app/admin'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/deposit'
    | '/app/market'
    | '/app/privacy'
    | '/app/profile'
    | '/app/sells'
    | '/app/support'
    | '/app/transactions'
    | '/app/withdrawals'
    | '/app/'
    | '/api/public/fx-refresh'
    | '/app/admin/content'
    | '/app/admin/deposits'
    | '/app/admin/products'
    | '/app/admin/users'
    | '/app/admin/withdrawals'
    | '/app/transactions/$txId'
    | '/app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiPublicFxRefreshRoute: typeof ApiPublicFxRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/withdrawals': {
      id: '/app/withdrawals'
      path: '/withdrawals'
      fullPath: '/app/withdrawals'
      preLoaderRoute: typeof AppWithdrawalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sells': {
      id: '/app/sells'
      path: '/sells'
      fullPath: '/app/sells'
      preLoaderRoute: typeof AppSellsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/privacy': {
      id: '/app/privacy'
      path: '/privacy'
      fullPath: '/app/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market': {
      id: '/app/market'
      path: '/market'
      fullPath: '/app/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deposit': {
      id: '/app/deposit'
      path: '/deposit'
      fullPath: '/app/deposit'
      preLoaderRoute: typeof AppDepositRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions/$txId': {
      id: '/app/transactions/$txId'
      path: '/$txId'
      fullPath: '/app/transactions/$txId'
      preLoaderRoute: typeof AppTransactionsTxIdRouteImport
      parentRoute: typeof AppTransactionsRoute
    }
    '/app/admin/withdrawals': {
      id: '/app/admin/withdrawals'
      path: '/admin/withdrawals'
      fullPath: '/app/admin/withdrawals'
      preLoaderRoute: typeof AppAdminWithdrawalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/products': {
      id: '/app/admin/products'
      path: '/admin/products'
      fullPath: '/app/admin/products'
      preLoaderRoute: typeof AppAdminProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/deposits': {
      id: '/app/admin/deposits'
      path: '/admin/deposits'
      fullPath: '/app/admin/deposits'
      preLoaderRoute: typeof AppAdminDepositsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/content': {
      id: '/app/admin/content'
      path: '/admin/content'
      fullPath: '/app/admin/content'
      preLoaderRoute: typeof AppAdminContentRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/fx-refresh': {
      id: '/api/public/fx-refresh'
      path: '/api/public/fx-refresh'
      fullPath: '/api/public/fx-refresh'
      preLoaderRoute: typeof ApiPublicFxRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppTransactionsRouteChildren {
  AppTransactionsTxIdRoute: typeof AppTransactionsTxIdRoute
}

const AppTransactionsRouteChildren: AppTransactionsRouteChildren = {
  AppTransactionsTxIdRoute: AppTransactionsTxIdRoute,
}

const AppTransactionsRouteWithChildren = AppTransactionsRoute._addFileChildren(
  AppTransactionsRouteChildren,
)

interface AppRouteChildren {
  AppDepositRoute: typeof AppDepositRoute
  AppMarketRoute: typeof AppMarketRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSellsRoute: typeof AppSellsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTransactionsRoute: typeof AppTransactionsRouteWithChildren
  AppWithdrawalsRoute: typeof AppWithdrawalsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminContentRoute: typeof AppAdminContentRoute
  AppAdminDepositsRoute: typeof AppAdminDepositsRoute
  AppAdminProductsRoute: typeof AppAdminProductsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminWithdrawalsRoute: typeof AppAdminWithdrawalsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDepositRoute: AppDepositRoute,
  AppMarketRoute: AppMarketRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppProfileRoute: AppProfileRoute,
  AppSellsRoute: AppSellsRoute,
  AppSupportRoute: AppSupportRoute,
  AppTransactionsRoute: AppTransactionsRouteWithChildren,
  AppWithdrawalsRoute: AppWithdrawalsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminContentRoute: AppAdminContentRoute,
  AppAdminDepositsRoute: AppAdminDepositsRoute,
  AppAdminProductsRoute: AppAdminProductsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminWithdrawalsRoute: AppAdminWithdrawalsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiPublicFxRefreshRoute: ApiPublicFxRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
