/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppWithdrawalsRouteImport } from './routes/app/withdrawals'
import { Route as AppTransactionsRouteImport } from './routes/app/transactions'
import { Route as AppSellsRouteImport } from './routes/app/sells'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppMarketRouteImport } from './routes/app/market'
import { Route as AppTransactionsTxIdRouteImport } from './routes/app/transactions.$txId'
import { Route as AppAdminWithdrawalsRouteImport } from './routes/app/admin.withdrawals'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWithdrawalsRoute = AppWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSellsRoute = AppSellsRouteImport.update({
  id: '/sells',
  path: '/sells',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsTxIdRoute = AppTransactionsTxIdRouteImport.update({
  id: '/$txId',
  path: '/$txId',
  getParentRoute: () => AppTransactionsRoute,
} as any)
const AppAdminWithdrawalsRoute = AppAdminWithdrawalsRouteImport.update({
  id: '/admin/withdrawals',
  path: '/admin/withdrawals',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/market': typeof AppMarketRoute
  '/app/profile': typeof AppProfileRoute
  '/app/sells': typeof AppSellsRoute
  '/app/transactions': typeof AppTransactionsRouteWithChildren
  '/app/withdrawals': typeof AppWithdrawalsRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/withdrawals': typeof AppAdminWithdrawalsRoute
  '/app/transactions/$txId': typeof AppTransactionsTxIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/market': typeof AppMarketRoute
  '/app/profile': typeof AppProfileRoute
  '/app/sells': typeof AppSellsRoute
  '/app/transactions': typeof AppTransactionsRouteWithChildren
  '/app/withdrawals': typeof AppWithdrawalsRoute
  '/app': typeof AppIndexRoute
  '/app/admin/withdrawals': typeof AppAdminWithdrawalsRoute
  '/app/transactions/$txId': typeof AppTransactionsTxIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/market': typeof AppMarketRoute
  '/app/profile': typeof AppProfileRoute
  '/app/sells': typeof AppSellsRoute
  '/app/transactions': typeof AppTransactionsRouteWithChildren
  '/app/withdrawals': typeof AppWithdrawalsRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/withdrawals': typeof AppAdminWithdrawalsRoute
  '/app/transactions/$txId': typeof AppTransactionsTxIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/market'
    | '/app/profile'
    | '/app/sells'
    | '/app/transactions'
    | '/app/withdrawals'
    | '/app/'
    | '/app/admin/withdrawals'
    | '/app/transactions/$txId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app/market'
    | '/app/profile'
    | '/app/sells'
    | '/app/transactions'
    | '/app/withdrawals'
    | '/app'
    | '/app/admin/withdrawals'
    | '/app/transactions/$txId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/market'
    | '/app/profile'
    | '/app/sells'
    | '/app/transactions'
    | '/app/withdrawals'
    | '/app/'
    | '/app/admin/withdrawals'
    | '/app/transactions/$txId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/withdrawals': {
      id: '/app/withdrawals'
      path: '/withdrawals'
      fullPath: '/app/withdrawals'
      preLoaderRoute: typeof AppWithdrawalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sells': {
      id: '/app/sells'
      path: '/sells'
      fullPath: '/app/sells'
      preLoaderRoute: typeof AppSellsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market': {
      id: '/app/market'
      path: '/market'
      fullPath: '/app/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions/$txId': {
      id: '/app/transactions/$txId'
      path: '/$txId'
      fullPath: '/app/transactions/$txId'
      preLoaderRoute: typeof AppTransactionsTxIdRouteImport
      parentRoute: typeof AppTransactionsRoute
    }
    '/app/admin/withdrawals': {
      id: '/app/admin/withdrawals'
      path: '/admin/withdrawals'
      fullPath: '/app/admin/withdrawals'
      preLoaderRoute: typeof AppAdminWithdrawalsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppTransactionsRouteChildren {
  AppTransactionsTxIdRoute: typeof AppTransactionsTxIdRoute
}

const AppTransactionsRouteChildren: AppTransactionsRouteChildren = {
  AppTransactionsTxIdRoute: AppTransactionsTxIdRoute,
}

const AppTransactionsRouteWithChildren = AppTransactionsRoute._addFileChildren(
  AppTransactionsRouteChildren,
)

interface AppRouteChildren {
  AppMarketRoute: typeof AppMarketRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSellsRoute: typeof AppSellsRoute
  AppTransactionsRoute: typeof AppTransactionsRouteWithChildren
  AppWithdrawalsRoute: typeof AppWithdrawalsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminWithdrawalsRoute: typeof AppAdminWithdrawalsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMarketRoute: AppMarketRoute,
  AppProfileRoute: AppProfileRoute,
  AppSellsRoute: AppSellsRoute,
  AppTransactionsRoute: AppTransactionsRouteWithChildren,
  AppWithdrawalsRoute: AppWithdrawalsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminWithdrawalsRoute: AppAdminWithdrawalsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
